version: '3'
services:
  jupyternotebook:
    image: jupyter/base-notebook
    container_name: jupyter.local
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./work:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''
